### ISSUE TITLE
Issue when connecting to REST catalogs on AWS ( Amazon SageMaker Lakehouse)

### ISSUE THREAD

**Issue by Neuw84** [apache/iceberg-python#1449]
### Apache Iceberg version

0.8.1 (latest release)

### Please describe the bug 🐞

Hi, 

I am trying to read and write from a RMS (Redshift Managed Storage) backed catalog on AWS. The thing is that I am trying configuring the REST catalog like this. 

```
rest_catalog = load_catalog(
    "rms-demo.dev",
    **{
        "type": "rest",
        "uri": "https://glue.us-east-2.amazonaws.com/iceberg",
             "rest.sigv4-enabled": "true",
               "rest.signing-name": "glue",
               "rest.signing-region": "us-east-2"
    }
)
```

But the thing is that the calls to the catalog goes through the default account id catalog. **Note the http call on the traceback**.   it should be showing "rms-demo.dev" on the url and instead is using the accountId. 

```
Traceback (most recent call last):
  File "/home/ec2-user/my_env/lib64/python3.9/site-packages/pyiceberg/catalog/rest.py", line 599, in _create_table
    response.raise_for_status()
  File "/home/ec2-user/my_env/lib64/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://glue.us-east-2.amazonaws.com/iceberg/v1/catalogs/accountId/namespaces/public/tables

The above exception was the direct cause of the following exception:
```

There is something in backend scenes on why it is injecting the AWs account id instead of using the catalog name? Tried to see on the code, but... 

Thanks!!

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by corleyma** [comment]
Unless something changed since I last looked at this (possible), I don't think Glue catalog supports the Iceberg REST spec?  There is a separate catalog client implementation in PyIceberg for Glue, in any case, and I assume that's what you want to use: https://py.iceberg.apache.org/reference/pyiceberg/catalog/glue/

**Comment by Neuw84** [comment]
yes, now we have an implementation of the REST catalog,

I know that reading from RMS data is not going to be possible yet but at least I was expecting that the HTTP calls to be redirected to the expected paths for the catalog. T

here should be something on the code causing that... ( I tried to search but didn´t found it).

**Comment by kevinjqliu** [comment]
I have not tested this personally but from reading the AWS blog on connect Spark to AWS Glue Iceberg REST catalog, there are some configurations that are different from what I would expect. 
https://aws.amazon.com/blogs/big-data/read-and-write-s3-iceberg-table-using-aws-glue-iceberg-rest-catalog-from-open-source-apache-spark/

```
import sys
import os
import time
from pyspark.sql import SparkSession

#Replace <aws_region> with AWS region name.
#Replace <aws_account_id> with AWS account ID.

spark = SparkSession.builder.appName('osspark') \
.config('spark.jars.packages', 'org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.1,software.amazon.awssdk:bundle:2.20.160,software.amazon.awssdk:url-connection-client:2.20.160') \
.config('spark.sql.extensions', 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions') \
.config('spark.sql.defaultCatalog', 'spark_catalog') \
.config('spark.sql.catalog.spark_catalog', 'org.apache.iceberg.spark.SparkCatalog') \
.config('spark.sql.catalog.spark_catalog.type', 'rest') \
.config('spark.sql.catalog.spark_catalog.uri','https://glue.<aws_region>.amazonaws.com/iceberg') \
.config('spark.sql.catalog.spark_catalog.warehouse','<aws_account_id>') \
.config('spark.sql.catalog.spark_catalog.rest.sigv4-enabled','true') \
.config('spark.sql.catalog.spark_catalog.rest.signing-name','glue') \
.config('spark.sql.catalog.spark_catalog.rest.signing-region', <aws_region>) \
.config('spark.sql.catalog.spark_catalog.io-impl','org.apache.iceberg.aws.s3.S3FileIO') \
.config('spark.hadoop.fs.s3a.aws.credentials.provider','org.apache.hadoop.fs.s3a.SimpleAWSCredentialProvider') \
.config('spark.sql.catalog.spark_catalog.rest-metrics-reporting-enabled','false') \
.getOrCreate()
```

Specifically, notice the `warehouse` parameter. It might help trying to replicate what this spark config is doing

**Comment by Neuw84** [comment]
Well for normal s3 buckets is working well without the parameter (have a working script that writes and read via the rest catalog).

Will try to dig on why is doing those weird calls.

**Comment by kevinjqliu** [comment]
can you share what you've tried that worked? Might be helpful to debug this further

**Comment by davidshtian** [comment]
Hi! Asking for help~ Wonder if SageMaker Lakehouse on RMS supported yet or not? (not S3 Tables)

```
from pyiceberg.catalog import load_catalog

REGION = 'us-east-1'
CATALOG = '<catalog name>'
ACCOUNT_ID = '<account id>'
DATABASE_NAME = 'public'
TABLE_NAME = '<table name>'

rest_catalog = load_catalog(
        CATALOG,
        **{
            "type": "rest",
            "warehouse": f"{ACCOUNT_ID}:{CATALOG}/dev",
            "uri": f"https://glue.{REGION}.amazonaws.com/iceberg",
            "rest.sigv4-enabled": "true",
            "rest.signing-name": "glue",
            "rest.signing-region": REGION
        }
    )

table = rest_catalog.load_table(
    f"{DATABASE_NAME}.{TABLE_NAME}"
)

print(f"Table: {table}")

scan = table.scan().to_pandas()

print(f"Scan: {scan}")
```

I've tried the codes above, the table info shown normally, while scan result not.

Good 😊
```
Table: tbl(
  1: id: optional int,
  2: name: optional string
),
partition by: [],
sort order: [],
snapshot: Operation.OVERWRITE: id=0, schema_id=0
```

Bad ☹️ and weird...
```
FileNotFoundError: [Errno 2] Failed to open local file '/home/ubuntu/<table name>'. Detail: [errno 2] No such file or directory
```

Thanks~

**Comment by davidshtian** [comment]
> Hi [@davidshtian](https://github.com/davidshtian), I'm facing a similar issue, even tried via spark, but I'm getting a similar issue. Also, found this interesting post, you can use logging to debug https://dev.to/aws-builders/glue-iceberg-rest-api-and-pyiceberg-364g In my case the issue is
> 
> ```
> warnings.warn(f"No preferred file implementation for scheme: {parsed_url.scheme}")
> 2025-05-21 10:52:28,157 - pyiceberg.io - INFO - Defaulting to PyArrow FileIO
> ```
> 
> And I think it has something to do with nested catalogs.

Thanks for your advice. I've tried direct API call using _awscurl_.
```
awscurl --service glue https://glue.us-east-1.amazonaws.com/iceberg/v1/catalogs/<account id>:<catalog name>/dev/namespaces/public/tables/<table name> | jq
```

and get result like this:
```
{
  "config": {
    "aws.server-side-capabilities.scan-planning": "true",
    "aws.glue.staging.data-transfer-role-arn": "xxx",
    "aws.glue.staging.location": "s3://redshift-staging-bucket-xxx/xxx:xxx/write/xxx/",
    "aws.glue.staging.expiration-ms": "1747882835000",
    "aws.glue.staging.session-token": "xxx",
    "aws.glue.staging.access-key-id": "xxx",
    "aws.glue.staging.secret-access-key": "xxx",
    "aws.server-side-capabilities.data-commit": "true"
  },
  "metadata": {
    "current-schema-id": 0,
    "current-snapshot-id": 0,
    "default-sort-order-id": 0,
    "default-spec-id": 0,
    "format-version": 2,
    "last-column-id": 2,
    "last-partition-id": 1000,
    "last-sequence-number": 0,
    "last-updated-ms": 0,
    "location": "tbl",
    "metadata-log": [],
    "partition-specs": [
      {
        "fields": [],
        "spec-id": 0
      }
    ],
    "properties": {
      "aws.write.format": "RMS",
      "schema.name-mapping.default": "[ {\n  \"field-id\" : 1,\n  \"names\" : [ \"id\" ]\n}, {\n  \"field-id\" : 2,\n  \"names\" : [ \"name\" ]\n} ]"
    },
    "refs": {
      "main": {
        "snapshot-id": 0,
        "type": "branch"
      }
    },
    "schemas": [
      {
        "fields": [
          {
            "id": 1,
            "name": "id",
            "required": false,
            "type": "int"
          },
          {
            "id": 2,
            "name": "name",
            "required": false,
            "type": "string"
          }
        ],
        "schema-id": 0,
        "type": "struct"
      }
    ],
    "snapshot-log": [
      {
        "snapshot-id": 0,
        "timestamp-ms": 0
      }
    ],
    "snapshots": [
      {
        "manifest-list": "<table name>",
        "parent-snapshot-id": 0,
        "schema-id": 0,
        "sequence-number": 0,
        "snapshot-id": 0,
        "summary": {},
        "timestamp-ms": 0
      }
    ],
    "sort-orders": [
      {
        "fields": [],
        "order-id": 0
      }
    ],
    "statistics-files": [],
    "table-uuid": "xxx"
  }
}
```

Weird for `"snapshots"` part in metadata json, `manifest-list` is just the table name, `schema-id` is always 0...

**Comment by davidshtian** [comment]
@lazara2 Thanks for your help~ The docs here are really helpful!

I've tried using Glue Extension endpoint, and yes the `list_tables` showed nothing. Then I found that there is `glue` method for this catalog, I can use that to show table info (actually it's proxying boto3). However, I still did not find the way to read the data via pyiceberg...
